### ISSUE TITLE
How correct work with ff R package

### ISSUE THREAD

**Issue by jasperDD** [Robinlovelace/R-for-Big-Data#7]
Hi!
That's my problem. I must  join two datasets by compare.linkage
simple example
s=compare.linkage(df1, df2, strcmp = c("id"), strcmpfun = jarowinkler), but  i work with very large data and RAM is not lack. The standart error message something like `cannot allocate vector of size 845.3 gb
`
r memory limited setted on max.

I found ff package , but can't uderstand how it works
there my data
For reproducible example i can give part of them

    df1=structure(list(id = structure(c(4L, 14L, 5L, 5L, 20L, 19L, 16L, 
    18L, 17L, 1L, 2L, 15L, 3L, 13L, 6L, 25L, 11L, 12L, 22L, 24L, 
    21L, 23L, 23L, 26L, 8L, 7L, 10L, 9L, 8L, 7L, 10L, 9L, 8L), .Label = c("A thin Proximity-card for applying the owner's photo.", 
    "A thin Proximity card with a magnetic strip for applying images to the card printer.", 
    "Active Proximity-tag for automotive accounting.", "Autonomous single-door controller with built-in Proximity card reader and 3x4 keyboard for programming.", 
    "Compact Proximity reader with reading distance up to 14 cm: Classic or Designer design.", 
    "Contactless card with MIFARE chip.", "Memory 16 KBits 2 sectors / Memory 16 KBits 16 sectors", 
    "Memory 2 KBits 2 sectors", "Memory 32 KBit 16K / 16 + 16K / 1", 
    "Memory 32 KBit 16K / 2 + 16K / 1", "MIFARE keychain.", "Miniature MIFARE-tag.", 
    "Miniature Proximity-tag.", "Miniature Proximity reader with reading distance up to 7.5 cm: Classic or Designer design.", 
    "Proximity-keychain.", "Proximity-reader with keyboard", "Proximity card with a slot for fastening.", 
    "Proximity reader with reading distance up to 180 cm (only with active ProxPass tags): Classic design.", 
    "Proximity reader with reading distance up to 20 cm: Classic design.", 
    "Proximity reader with reading distance up to 22 cm: Classic design.", 
    "Reader contactless Smart-card with a keyboard with reading distance up to 10.1 cm (read / write).", 
    "Reader of contactless Smart-cards with reading distance up to 7.6 cm (read / write). Light indication: 3-color LED.", 
    "Reader of contactless Smart-cards with reading distance up to 8.9 cm (read / write)", 
    "Reader of contactless Smart-cards with readout distance up to 11.4 cm (read / write). Light indication: 3-color LED.", 
    "Thin card dual technology Proximity + MIFARE.", "Wear-resistant Smart-card iClass. Thick map"
    ), class = "factor")), .Names = "id", class = "data.frame", row.names = c(NA, 
    -33L))
    

df2=

    structure(list(X.Fire.extinguisher...200х200..Plastic.PVC.2mm.UV.printing. = structure(c(20L, 
    4L, 5L, 11L, 12L, 14L, 15L, 9L, 10L, 13L, 14L, 1L, 8L, 19L, 2L, 
    3L, 22L, 7L, 6L, 21L, 17L, 16L, 18L), .Label = c("\"Atlanta\" (complete: bath \"Atlanta\" 1200 liters, dental spinal traction system (electronic), set of belts and belts, lift with couch (electric drive, built-in battery), emergency button for stopping the procedure, step, PDM hose with 4 removable nozzles, neck traction, underwater eromassage system 120 nozzles, 32 powerful LEDs for the system \"WaterLight\" for chromotherapy, electronic control, color LCD display, intuitive interface). Overall dimensions of the complex (LxWxH), mm, not more than 2610х1050х1400 (2000). Bath weight, kg 225. Color white.", 
    "\"Attention danger\" ZK176 (PVC plastic 2 mm UV printing; 200x250)", 
    "\"Attention! Entrance without a helmet is forbidden\" ZK096 (PVC plastic 2 mm UV printing; 450x600)", 
    "\"Emergency exit\" DP28 (Plastic PVC 2 mm UV printing; 300x150)", 
    "\"Emergency exit\" DP28 (Self-adhesive PVC film; 300x150)", 
    "\"Entry by strangers is forbidden\" ZK099 (PVC plastic 2 mm UV print; 200x250)", 
    "\"Entry is not allowed to outsiders\" ZK099 (200 * 250; PVC plastic 2mm UV seal)", 
    "\"Explosive\" ZK183 (PVC plastic 2 mm UV printing; 450x600)", 
    "\"First-aid kit\" EC01 (Self-adhesive photoluminescent film; 100x100)", 
    "\"First-aid kit\" EC01 (Self-adhesive PVC film; 100x100)", "\"First Aid Kit\" EC01 (Plastic PVC 2 mm with photoluminescent film 100х100)", 
    "\"First Aid Kit\" EC01 (Plastic PVC 2 mm with photoluminescent film 150х150)", 
    "\"First Aid Kit\" EC01 (Plastic PVC 2 mm with photoluminescent film 250х250)", 
    "\"First Aid Kit\" EC01 (Plastic PVC 2 mm with photoluminescent film 300х300)", 
    "\"First Aid Kit\" EC01 (Plastic PVC 2 mm with photoluminescent film; 200х200)", 
    "\"Gas! Entry is prohibited\" (D700 mm, metal 1 mm polymer color on both sides Z-shaped gas-watertight connections double continuous flanging)", 
    "\"Gas, Explosive., Fire\" (300 * 200; Plastic PVC 2mm UV printing)", 
    "\"Gas: Entry by strangers is forbidden\" (300 * 150; PVC plastic 2mm UV printing)", 
    "\"Get in here\", portable with polyester cord A12 (PVC plastic 2 mm UV print; 250x250)", 
    "\"Index of emergency exit\" E23 (300x150; PVC plastic 2mm, with photoluminescent film)", 
    "\"Input\" DP172 (Plastic PVC 2 mm UV printing; 300x150)", "\"Warning: Protected area\" 300х400 PVC plastic 2 mm UV seal"
    ), class = "factor")), .Names = "X.Fire.extinguisher...200х200..Plastic.PVC.2mm.UV.printing.", class = "data.frame", row.names = c(NA, 
    -23L))
     i do so.
  library("ff")
    df1<- read.csv.ffdf(file="1.csv", header=TRUE)
    df2<- read.csv.ffdf(file="/pot.csv", sep=";", header=TRUE)
    library(RecordLinkage)

    s=compare.linkage(df1, df2, strcmp = c("id"), strcmpfun = jarowinkler)

 i get the error

    Error in compare.linkage(df1, df2, strcmp = c("id"), strcmpfun = jarowinkler) : 
      Illegal format of dataset1

I understand that i do anything wrong and i need advice.

How can I optimize the work with memory, when working with large data using this library?

**Comment by Robinlovelace** [comment]
There is a description of ff here: http://ff.r-forge.r-project.org/bit&ff2.1-2_WU_Vienna2010.pdf

Other resources can be found but I've found few recent resources. Planning to archive this content so closing this issue - please head over to https://github.com/csgillespie/efficientR for more up-to-date advice.

Thanks!
